language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
    - php: 7
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit --colors tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | xargs -n1 php -d display_errors=stderr -l
